# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppOption',
        ),
    ]
