# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdata',
            name='modbus_id',
            field=models.IntegerField(default=0, verbose_name='modbus address'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='pvi_name',
            field=models.CharField(default='', max_length=20, verbose_name='pvi name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regdata',
            name='address',
            field=models.IntegerField(verbose_name='register address'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='date',
            field=models.DateTimeField(verbose_name='log datetime'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='sync_flag',
            field=models.BooleanField(default=False, verbose_name='sync flag with cloud'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='register read value'),
        ),
    ]
