# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvi', '0002_auto_20151217_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdata',
            name='pvi_name',
            field=models.CharField(default='', max_length=20, verbose_name='pvi name'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='value',
            field=models.IntegerField(default=0, verbose_name='register read value'),
        ),
    ]
