# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import pvi.models


class Migration(migrations.Migration):

    dependencies = [
        ('pvi', '0003_auto_20151217_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdata',
            name='prob_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='log date'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='prob_hour',
            field=models.IntegerField(default=pvi.models.get_current_time_hour, verbose_name='hour of log time'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='prob_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='log time'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='log datetime'),
        ),
    ]
