# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pvi', '0004_auto_20151228_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modbus_id', models.IntegerField(default=0, verbose_name='modbus address')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='energy date')),
                ('type', models.CharField(default='', max_length=20, verbose_name='energy type')),
                ('value', models.IntegerField(default=0, verbose_name='energy value')),
                ('sync_flag', models.BooleanField(default=False, verbose_name='sync flag')),
            ],
        ),
    ]
