# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccuWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_date', models.DateField(default=datetime.datetime.now)),
                ('prob_time', models.TimeField(default=datetime.datetime.now)),
                ('prob_hour', models.IntegerField()),
                ('temperature', models.FloatField(default=0.0)),
                ('uv', models.IntegerField(default=0)),
                ('visibility', models.FloatField(default=0.0)),
                ('sync_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
