# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accuweather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccuWeather',
            new_name='CurrConditions',
        ),
    ]
